### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jackfirth** [sorawee/fmt#15]
For testing resyntax, I wrote `#lang resyntax/testing/refactoring-test` so I could easily write tests like [this](https://github.com/jackfirth/resyntax/blob/master/default-recommendations/for-loop-shortcuts-test.rkt). Is that an approach that would benefit `fmt` as well?

**Comment by sorawee** [comment]
Thanks for the offer!

I have tests in the directory https://github.com/sorawee/fmt/tree/master/tests. After I change `fmt`, I would run [`regen.rkt`](https://github.com/sorawee/fmt/blob/master/regen.rkt) to regenerate all formatted files. Then, I would manually inspect the diff when I'm about the commit the change. This seems like a perfect workflow since I want to see the effect of the change anyway.

Since formatting is mostly about aesthetics, there's no hard specification, so I think a rigid testing framework might not be worth it (or at least, not worth it at the current stage of development).

Therefore, I think I will close this issue, but if you have any thoughts, let me know!
