### ISSUE TITLE
How to use the CLI option --config

### ISSUE THREAD

**Issue by bitst0rm** [sorawee/fmt#52]
There is an undocumented option `--config`
`raco fmt --config /path/to/myconfig.rkt`

I am not familiar with Racket. Instead of using CLI option `--xxx` directly, could you please provide an example to use user-config file with formatting rules like this:
_myconfig.rkt_:
```
width 60
limit 80
max-blank-lines 0
indent 3
```
Thanks!

**Comment by sorawee** [comment]
It is undocumented because it is unstable, and more of a proof-of-concept. But if you don't mind that, you can take a look at 

- https://github.com/sorawee/fmt/blob/master/tests/config-tests/config.rkt
- https://github.com/sorawee/fmt/blob/master/.fmt.rkt

for examples. Feel free to let me know if you have any further questions.
